<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<meta content="IE=edge, chrome=1" http-equiv="X-UA-Compatible">
	<meta name="author" content="Jardel Frank - YCLE">
	<title><?php echo $this->getPageTitle('|') ?> Y-PHP</title>
	<link rel="shortcut icon" href="/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
	<main class="container">
		<?php require_once __DIR__."/partial/menu.phtml" ?>
		<?php $this->content() ?>
	</main>
	
	<script type="text/javascript" src="/js/app.js"></script>
</body>
</html>
